version: "3"
services:
  myapp:
    build: .
    image: jaemok-image
    container_name: jaemok-container
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  redis:
    image: redis
    container_name: redis
    command: redis-server --port 6379
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis/data:/data
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
